version: "3.9"

services:
#  gahlification_backend:
#    container_name: gahlification_backend
##    image: jackalgera/gahlification_backend:latest
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      JDBC_DATABASE_URL: 'jdbc:postgresql://gahlification_database:5432/postgres?password=database_password&user=database_user'
#      USERNAME: 'jack'
#      PASSWORD: '$2a$10$YV.QV0pabaaT4w15CcV0bOUbmnU1laqPUzMh50NJ4pviZi4wpCRgW'
#      SECRET: 'jack'
#    depends_on:
#      - gahlification_database

  gahlification_database:
    container_name: gahlification_database
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: database_user
      POSTGRES_PASSWORD: database_password
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgres/data/pgdata
    volumes:
      - gahlification_database:/var/lib/postgres
    restart: unless-stopped

volumes:
  gahlification_database:
