version: "3.9"

services:
#  gahlification_backend:
#    container_name: gahlification_backend
##    image: jackalgera/gahlification_backend:latest
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      DATABASE_INSTANCE: 'gahlification_database:5432'
#      DATABASE_NAME: gahlification_db
#      DATABASE_USER_NAME: gahlification_user
#      DATABASE_PASSWORD: gahlification_password
#    depends_on:
#      - gahlification_database

  gahlification_database:
    container_name: gahlification_database
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gahlification_user
      POSTGRES_PASSWORD: gahlification_password
      POSTGRES_DB: gahlification_db
      PGDATA: /var/lib/postgres/data/pgdata
    volumes:
      - gahlification_database:/var/lib/postgres
    restart: unless-stopped

volumes:
  gahlification_database:
