version: "3.9"

services:
  gahlification_backend:
    container_name: gahlification_backend
#    image: jackalgera/gahlification_backend:latest
    build: .
    ports:
      - "8080:8080"
    environment:
#      DATABASE_INSTANCE: 'localhost:5432'
#      DATABASE_NAME: postgres
#      DATABASE_USER_NAME: database_user
#      DATABASE_PASSWORD: database_password
      JDBC_DATABASE_URL: 'jdbc:postgresql://gahlification_database:5432/postgres?password=database_password&user=database_user'
    depends_on:
      - gahlification_database

  gahlification_database:
    container_name: gahlification_database
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: database_user
      POSTGRES_PASSWORD: database_password
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgres/data/pgdata
    volumes:
      - gahlification_database:/var/lib/postgres
    restart: unless-stopped

volumes:
  gahlification_database:
