app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: ${JDBC_DATABASE_URL}
      pool-size: 30
spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    property-naming-strategy: "LOWER_CAMEL_CASE"

server:
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never
  servlet:
    context-path: "/api"
  port: ${PORT:5000}

jwt:
  secret: jack
