apiVersion: apps/v1
kind: Deployment
metadata:
  name: gahlification-backend
  labels:
    app: gahlification-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gahlification-backend
  template:
    metadata:
      labels:
        app: gahlification-backend
    spec:
      containers:
        - name: gahlification-backend-api
          image: "okteto.dev/gahlification_backend:latest"
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DATABASE_INSTANCE
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: database_instance
            - name: DATABASE_USER_NAME
              valueFrom:
                configMapKeyRef:
                  name: database-credentials
                  key: database_user_name
            - name: DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: database-credentials
                  key: database_password
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: database_name
