apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
data:
  database_user_name: Z2FobGlmaWNhdGlvbl91c2Vy # gahlification_user
  database_password: Z2FobGlmaWNhdGlvbl9wYXNzd29yZA== # gahlification_password
