apiVersion: v1
kind: Service
metadata:
  name: home-cluster-service
  labels:
    app: home-cluster-backend
spec:
  selector:
    app: home-cluster-backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
